name: Deploy to ECR
# updated ECR Repo week3-1
on: 
  push:
    branches: [ dev ]

jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest


    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_APP_REPOSITORY: clo835-jcaranay-assignment1-app-repo
        ECR_DB_REPOSITORY: clo835-jcaranay-assignment1-db-repo
        OLD_IMAGE_TAG: v0.1
        NEW_IMAGE_TAG: v0.2
        APP_COLOR: Blue
      run: |
        ls -ltra
        # Docker build command
        # Database
        echo Build Database
        docker build -t $ECR_REGISTRY/$ECR_DB_REPOSITORY:$OLD_IMAGE_TAG -f Dockerfile_mysql .


        # Application
        echo Build Application
        docker build -t $ECR_REGISTRY/$ECR_APP_REPOSITORY:$OLD_IMAGE_TAG -f Dockerfile .


        # Unit test
        # Run the database
        echo Run Database
        docker run -d -e MYSQL_ROOT_PASSWORD=${{ secrets.DBPWD }} $ECR_REGISTRY/$ECR_DB_REPOSITORY:$OLD_IMAGE_TAG 
        
        echo Run Application
        docker run -p 8081:8080 \
        -e APP_COLOR=$APP_COLOR \
        -e DBHOST=${{ secrets.DBHOST }} \
        -e DBPORT=${{ secrets.DBPORT }} \
        -e DBUSER=${{ secrets.DBUSER }} \
        -e DBPWD=${{ secrets.DBPWD }} \
        $ECR_REGISTRY/$ECR_APP_REPOSITORY:$OLD_IMAGE_TAG 
               
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        curl localhost:8081 -vvv

        # Push image to ECR REPO DB and APP
        docker push $ECR_REGISTRY/$ECR_DB_REPOSITORY:$NEW_IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_APP_REPOSITORY:$NEW_IMAGE_TAG
